[workspace]
members = ["crates/katex"]
default-members = ["crates/katex"]
resolver = "3"

[workspace.package]
edition = "2024"

[workspace.metadata]
repository = "https://github.com/katex-rs/katex-rs"

[profile.release]
opt-level = "z"
lto = "fat"
